spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://127.0.0.1:3306/bikepartstore?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  sql:
    init:
      mode: always
